jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project deps
        run: |
            pip install .[training]

      - name: Train model
        run: |
          train-spam-model --version ${{ github.ref_name }}
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      # - name: Upload model artifacts for next job
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: model_artifacts
      #     path: models/${{ github.ref_name }}
